package files;

public class BodyContent {
	public String inputBodyContent() {
		return "{\r\n"
				+ "  \"location\": {\r\n"
				+ "    \"lat\": -38.383494,\r\n"
				+ "    \"lng\": 33.427362\r\n"
				+ "  },\r\n"
				+ "  \"accuracy\": 50,\r\n"
				+ "  \"name\": \"hoi house\",\r\n"
				+ "  \"phone_number\": \"(+91) 983 893 3937\",\r\n"
				+ "  \"address\": \"29, side layout, cohen 09\",\r\n"
				+ "  \"types\": [\r\n"
				+ "    \"shoe park\",\r\n"
				+ "    \"shop\"\r\n"
				+ "  ],\r\n"
				+ "  \"website\": \"http://google.com\",\r\n"
				+ "  \"language\": \"French-IN\"\r\n"
				+ "}";
		
	}
	
	public String nestedJson() {
		return "{\r\n"
				+ "\r\n"
				+ "\"dashboard\": {\r\n"
				+ "\r\n"
				+ "\"purchaseAmount\": 910,\r\n"
				+ "\r\n"
				+ "\"website\": \"rahulshettyacademy.com\"\r\n"
				+ "\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "\"courses\": [\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\r\n"
				+ "\"title\": \"Selenium Python\",\r\n"
				+ "\r\n"
				+ "\"price\": 50,\r\n"
				+ "\r\n"
				+ "\"copies\": 6\r\n"
				+ "\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\r\n"
				+ "\"title\": \"Cypress\",\r\n"
				+ "\r\n"
				+ "\"price\": 40,\r\n"
				+ "\r\n"
				+ "\"copies\": 4\r\n"
				+ "\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\r\n"
				+ "\"title\": \"RPA\",\r\n"
				+ "\r\n"
				+ "\"price\": 45,\r\n"
				+ "\r\n"
				+ "\"copies\": 10\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "]\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "";
	}
	
	public String bodyDynamicJson(String isbn, String aisle) {
		return "{\r\n"
				+ "\"name\":\"Learn REST\",\r\n"
				+ "\"isbn\":\""+isbn+"\",\r\n"
				+ "\"aisle\":\""+aisle+"\",\r\n"
				+ "\"author\":\"jacob andrew\"\r\n"
				+ "}\r\n"
				+ "";
	}
	
	public String hey() {
		
		return "{\r\n"
				+ "    \"expand\": \"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations\",\r\n"
				+ "    \"id\": \"10100\",\r\n"
				+ "    \"self\": \"http://localhost:8080/rest/api/2/issue/10100\",\r\n"
				+ "    \"key\": \"RESTAPI-2\",\r\n"
				+ "    \"fields\": {\r\n"
				+ "        \"issuetype\": {\r\n"
				+ "            \"self\": \"http://localhost:8080/rest/api/2/issuetype/10004\",\r\n"
				+ "            \"id\": \"10004\",\r\n"
				+ "            \"description\": \"A problem which impairs or prevents the functions of the product.\",\r\n"
				+ "            \"iconUrl\": \"http://localhost:8080/secure/viewavatar?size=xsmall&avatarId=10303&avatarType=issuetype\",\r\n"
				+ "            \"name\": \"Bug\",\r\n"
				+ "            \"subtask\": false,\r\n"
				+ "            \"avatarId\": 10303\r\n"
				+ "        },\r\n"
				+ "        \"timespent\": null,\r\n"
				+ "        \"project\": {\r\n"
				+ "            \"self\": \"http://localhost:8080/rest/api/2/project/10000\",\r\n"
				+ "            \"id\": \"10000\",\r\n"
				+ "            \"key\": \"RESTAPI\",\r\n"
				+ "            \"name\": \"RESTAPITesting\",\r\n"
				+ "            \"projectTypeKey\": \"software\",\r\n"
				+ "            \"avatarUrls\": {\r\n"
				+ "                \"48x48\": \"http://localhost:8080/secure/projectavatar?avatarId=10324\",\r\n"
				+ "                \"24x24\": \"http://localhost:8080/secure/projectavatar?size=small&avatarId=10324\",\r\n"
				+ "                \"16x16\": \"http://localhost:8080/secure/projectavatar?size=xsmall&avatarId=10324\",\r\n"
				+ "                \"32x32\": \"http://localhost:8080/secure/projectavatar?size=medium&avatarId=10324\"\r\n"
				+ "            }\r\n"
				+ "        },\r\n"
				+ "        \"fixVersions\": [],\r\n"
				+ "        \"customfield_10110\": null,\r\n"
				+ "        \"customfield_10111\": null,\r\n"
				+ "        \"aggregatetimespent\": null,\r\n"
				+ "        \"resolution\": null,\r\n"
				+ "        \"customfield_10107\": null,\r\n"
				+ "        \"customfield_10108\": null,\r\n"
				+ "        \"customfield_10109\": null,\r\n"
				+ "        \"resolutiondate\": null,\r\n"
				+ "        \"workratio\": -1,\r\n"
				+ "        \"lastViewed\": null,\r\n"
				+ "        \"watches\": {\r\n"
				+ "            \"self\": \"http://localhost:8080/rest/api/2/issue/RESTAPI-2/watchers\",\r\n"
				+ "            \"watchCount\": 1,\r\n"
				+ "            \"isWatching\": true\r\n"
				+ "        },\r\n"
				+ "        \"created\": \"2023-04-25T15:26:03.036-0700\",\r\n"
				+ "        \"priority\": {\r\n"
				+ "            \"self\": \"http://localhost:8080/rest/api/2/priority/3\",\r\n"
				+ "            \"iconUrl\": \"http://localhost:8080/images/icons/priorities/medium.svg\",\r\n"
				+ "            \"name\": \"Medium\",\r\n"
				+ "            \"id\": \"3\"\r\n"
				+ "        },\r\n"
				+ "        \"customfield_10100\": \"0|i00007:\",\r\n"
				+ "        \"customfield_10101\": null,\r\n"
				+ "        \"customfield_10102\": null,\r\n"
				+ "        \"labels\": [],\r\n"
				+ "        \"timeestimate\": null,\r\n"
				+ "        \"aggregatetimeoriginalestimate\": null,\r\n"
				+ "        \"versions\": [],\r\n"
				+ "        \"issuelinks\": [],\r\n"
				+ "        \"assignee\": null,\r\n"
				+ "        \"updated\": \"2023-04-25T16:16:01.675-0700\",\r\n"
				+ "        \"status\": {\r\n"
				+ "            \"self\": \"http://localhost:8080/rest/api/2/status/10000\",\r\n"
				+ "            \"description\": \"\",\r\n"
				+ "            \"iconUrl\": \"http://localhost:8080/\",\r\n"
				+ "            \"name\": \"To Do\",\r\n"
				+ "            \"id\": \"10000\",\r\n"
				+ "            \"statusCategory\": {\r\n"
				+ "                \"self\": \"http://localhost:8080/rest/api/2/statuscategory/2\",\r\n"
				+ "                \"id\": 2,\r\n"
				+ "                \"key\": \"new\",\r\n"
				+ "                \"colorName\": \"default\",\r\n"
				+ "                \"name\": \"To Do\"\r\n"
				+ "            }\r\n"
				+ "        },\r\n"
				+ "        \"components\": [],\r\n"
				+ "        \"timeoriginalestimate\": null,\r\n"
				+ "        \"description\": \"Creating of an issue using project keys and issue type names using the REST API\",\r\n"
				+ "        \"timetracking\": {},\r\n"
				+ "        \"archiveddate\": null,\r\n"
				+ "        \"attachment\": [],\r\n"
				+ "        \"aggregatetimeestimate\": null,\r\n"
				+ "        \"summary\": \"From janani summary\",\r\n"
				+ "        \"creator\": {\r\n"
				+ "            \"self\": \"http://localhost:8080/rest/api/2/user?username=janani\",\r\n"
				+ "            \"name\": \"janani\",\r\n"
				+ "            \"key\": \"JIRAUSER10000\",\r\n"
				+ "            \"emailAddress\": \"jansree90@gmail.com\",\r\n"
				+ "            \"avatarUrls\": {\r\n"
				+ "                \"48x48\": \"https://www.gravatar.com/avatar/8ce96f4f756985f34cd8adeda8ce053f?d=mm&s=48\",\r\n"
				+ "                \"24x24\": \"https://www.gravatar.com/avatar/8ce96f4f756985f34cd8adeda8ce053f?d=mm&s=24\",\r\n"
				+ "                \"16x16\": \"https://www.gravatar.com/avatar/8ce96f4f756985f34cd8adeda8ce053f?d=mm&s=16\",\r\n"
				+ "                \"32x32\": \"https://www.gravatar.com/avatar/8ce96f4f756985f34cd8adeda8ce053f?d=mm&s=32\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"jansree90@gmail.com\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"timeZone\": \"America/Los_Angeles\"\r\n"
				+ "        },\r\n"
				+ "        \"subtasks\": [],\r\n"
				+ "        \"reporter\": {\r\n"
				+ "            \"self\": \"http://localhost:8080/rest/api/2/user?username=janani\",\r\n"
				+ "            \"name\": \"janani\",\r\n"
				+ "            \"key\": \"JIRAUSER10000\",\r\n"
				+ "            \"emailAddress\": \"jansree90@gmail.com\",\r\n"
				+ "            \"avatarUrls\": {\r\n"
				+ "                \"48x48\": \"https://www.gravatar.com/avatar/8ce96f4f756985f34cd8adeda8ce053f?d=mm&s=48\",\r\n"
				+ "                \"24x24\": \"https://www.gravatar.com/avatar/8ce96f4f756985f34cd8adeda8ce053f?d=mm&s=24\",\r\n"
				+ "                \"16x16\": \"https://www.gravatar.com/avatar/8ce96f4f756985f34cd8adeda8ce053f?d=mm&s=16\",\r\n"
				+ "                \"32x32\": \"https://www.gravatar.com/avatar/8ce96f4f756985f34cd8adeda8ce053f?d=mm&s=32\"\r\n"
				+ "            },\r\n"
				+ "            \"displayName\": \"jansree90@gmail.com\",\r\n"
				+ "            \"active\": true,\r\n"
				+ "            \"timeZone\": \"America/Los_Angeles\"\r\n"
				+ "        },\r\n"
				+ "        \"customfield_10000\": \"{summaryBean=com.atlassian.jira.plugin.devstatus.rest.SummaryBean@76a04e3[summary={pullrequest=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@6064cbd0[overall=PullRequestOverallBean{stateCount=0, state='OPEN', details=PullRequestOverallDetails{openCount=0, mergedCount=0, declinedCount=0}},byInstanceType={}], build=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@10f65287[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BuildOverallBean@560a3102[failedBuildCount=0,successfulBuildCount=0,unknownBuildCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], review=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@7e302662[overall=com.atlassian.jira.plugin.devstatus.summary.beans.ReviewsOverallBean@43c55d36[stateCount=0,state=<null>,dueDate=<null>,overDue=false,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], deployment-environment=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@61855da3[overall=com.atlassian.jira.plugin.devstatus.summary.beans.DeploymentOverallBean@6600f2b0[topEnvironments=[],showProjects=false,successfulCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], repository=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@197ccb24[overall=com.atlassian.jira.plugin.devstatus.summary.beans.CommitOverallBean@703909d0[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], branch=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@3b1a2a31[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BranchOverallBean@5aeeca90[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}]},errors=[],configErrors=[]], devSummaryJson={\\\"cachedValue\\\":{\\\"errors\\\":[],\\\"configErrors\\\":[],\\\"summary\\\":{\\\"pullrequest\\\":{\\\"overall\\\":{\\\"count\\\":0,\\\"lastUpdated\\\":null,\\\"stateCount\\\":0,\\\"state\\\":\\\"OPEN\\\",\\\"details\\\":{\\\"openCount\\\":0,\\\"mergedCount\\\":0,\\\"declinedCount\\\":0,\\\"total\\\":0},\\\"open\\\":true},\\\"byInstanceType\\\":{}},\\\"build\\\":{\\\"overall\\\":{\\\"count\\\":0,\\\"lastUpdated\\\":null,\\\"failedBuildCount\\\":0,\\\"successfulBuildCount\\\":0,\\\"unknownBuildCount\\\":0},\\\"byInstanceType\\\":{}},\\\"review\\\":{\\\"overall\\\":{\\\"count\\\":0,\\\"lastUpdated\\\":null,\\\"stateCount\\\":0,\\\"state\\\":null,\\\"dueDate\\\":null,\\\"overDue\\\":false,\\\"completed\\\":false},\\\"byInstanceType\\\":{}},\\\"deployment-environment\\\":{\\\"overall\\\":{\\\"count\\\":0,\\\"lastUpdated\\\":null,\\\"topEnvironments\\\":[],\\\"showProjects\\\":false,\\\"successfulCount\\\":0},\\\"byInstanceType\\\":{}},\\\"repository\\\":{\\\"overall\\\":{\\\"count\\\":0,\\\"lastUpdated\\\":null},\\\"byInstanceType\\\":{}},\\\"branch\\\":{\\\"overall\\\":{\\\"count\\\":0,\\\"lastUpdated\\\":null},\\\"byInstanceType\\\":{}}}},\\\"isStale\\\":false}}\",\r\n"
				+ "        \"aggregateprogress\": {\r\n"
				+ "            \"progress\": 0,\r\n"
				+ "            \"total\": 0\r\n"
				+ "        },\r\n"
				+ "        \"environment\": null,\r\n"
				+ "        \"duedate\": null,\r\n"
				+ "        \"progress\": {\r\n"
				+ "            \"progress\": 0,\r\n"
				+ "            \"total\": 0\r\n"
				+ "        },\r\n"
				+ "        \"comment\": {\r\n"
				+ "            \"comments\": [\r\n"
				+ "                {\r\n"
				+ "                    \"self\": \"http://localhost:8080/rest/api/2/issue/10100/comment/10000\",\r\n"
				+ "                    \"id\": \"10000\",\r\n"
				+ "                    \"author\": {\r\n"
				+ "                        \"self\": \"http://localhost:8080/rest/api/2/user?username=janani\",\r\n"
				+ "                        \"name\": \"janani\",\r\n"
				+ "                        \"key\": \"JIRAUSER10000\",\r\n"
				+ "                        \"emailAddress\": \"jansree90@gmail.com\",\r\n"
				+ "                        \"avatarUrls\": {\r\n"
				+ "                            \"48x48\": \"https://www.gravatar.com/avatar/8ce96f4f756985f34cd8adeda8ce053f?d=mm&s=48\",\r\n"
				+ "                            \"24x24\": \"https://www.gravatar.com/avatar/8ce96f4f756985f34cd8adeda8ce053f?d=mm&s=24\",\r\n"
				+ "                            \"16x16\": \"https://www.gravatar.com/avatar/8ce96f4f756985f34cd8adeda8ce053f?d=mm&s=16\",\r\n"
				+ "                            \"32x32\": \"https://www.gravatar.com/avatar/8ce96f4f756985f34cd8adeda8ce053f?d=mm&s=32\"\r\n"
				+ "                        },\r\n"
				+ "                        \"displayName\": \"jansree90@gmail.com\",\r\n"
				+ "                        \"active\": true,\r\n"
				+ "                        \"timeZone\": \"America/Los_Angeles\"\r\n"
				+ "                    },\r\n"
				+ "                    \"body\": \"Updating janani comment\",\r\n"
				+ "                    \"updateAuthor\": {\r\n"
				+ "                        \"self\": \"http://localhost:8080/rest/api/2/user?username=janani\",\r\n"
				+ "                        \"name\": \"janani\",\r\n"
				+ "                        \"key\": \"JIRAUSER10000\",\r\n"
				+ "                        \"emailAddress\": \"jansree90@gmail.com\",\r\n"
				+ "                        \"avatarUrls\": {\r\n"
				+ "                            \"48x48\": \"https://www.gravatar.com/avatar/8ce96f4f756985f34cd8adeda8ce053f?d=mm&s=48\",\r\n"
				+ "                            \"24x24\": \"https://www.gravatar.com/avatar/8ce96f4f756985f34cd8adeda8ce053f?d=mm&s=24\",\r\n"
				+ "                            \"16x16\": \"https://www.gravatar.com/avatar/8ce96f4f756985f34cd8adeda8ce053f?d=mm&s=16\",\r\n"
				+ "                            \"32x32\": \"https://www.gravatar.com/avatar/8ce96f4f756985f34cd8adeda8ce053f?d=mm&s=32\"\r\n"
				+ "                        },\r\n"
				+ "                        \"displayName\": \"jansree90@gmail.com\",\r\n"
				+ "                        \"active\": true,\r\n"
				+ "                        \"timeZone\": \"America/Los_Angeles\"\r\n"
				+ "                    },\r\n"
				+ "                    \"created\": \"2023-04-25T16:08:39.809-0700\",\r\n"
				+ "                    \"updated\": \"2023-04-25T16:16:01.675-0700\",\r\n"
				+ "                    \"visibility\": {\r\n"
				+ "                        \"type\": \"role\",\r\n"
				+ "                        \"value\": \"Administrators\"\r\n"
				+ "                    }\r\n"
				+ "                }\r\n"
				+ "            ],\r\n"
				+ "            \"maxResults\": 1,\r\n"
				+ "            \"total\": 1,\r\n"
				+ "            \"startAt\": 0\r\n"
				+ "        },\r\n"
				+ "        \"votes\": {\r\n"
				+ "            \"self\": \"http://localhost:8080/rest/api/2/issue/RESTAPI-2/votes\",\r\n"
				+ "            \"votes\": 0,\r\n"
				+ "            \"hasVoted\": false\r\n"
				+ "        },\r\n"
				+ "        \"worklog\": {\r\n"
				+ "            \"startAt\": 0,\r\n"
				+ "            \"maxResults\": 20,\r\n"
				+ "            \"total\": 0,\r\n"
				+ "            \"worklogs\": []\r\n"
				+ "        },\r\n"
				+ "        \"archivedby\": null\r\n"
				+ "    }\r\n"
				+ "}";
	}	

}
